[package]
authors = ["Eric Trombly <etrombly@gmail.com>"]
description = "Rust library for OsmGpsMap-1.0"
license = "MIT"
keywords = ["openstreetmap", "gtk", "map", "widget"]
name = "osmgpsmap"
readme = "README.md"
repository = "https://github.com/etrombly/osmgpsmap-rs"
version = "0.2.2"

[dependencies]
osmgpsmap-sys = "0.2.2"
gdk = "0.9.0"
gdk-pixbuf = "0.5.0"
glib = "0.6.0"
glib-sys = "0.7.0"
gobject-sys = "0.7.0"
gtk = "0.5.0"
gtk-sys = "0.7.0"
libc = "0.2.43"

[dependencies.cairo-rs]
version = "0.5.0"
#path = "../cairo"
features = ["use_glib"]

[dev-dependencies]
gio = "0.5.0"
